# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1094053b375663b4c4d4475488c55cd08bfab7c8f311dc5b48abb443d75598806565ff2638caa15761b7d8e405432d1ad6649153cfb12a1be3fae22c7232f5fb

test:
  secret_key_base: 712d7cfc56dc67c940c6cb4ac75d422e6f73b447fa316fc024f724402c970ee17c5e868c39bde95690c6fcee09917edb908b86b3f9b48205f7ee056cc21f5113

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
